### ISSUE TITLE
Add/format Open Trivia DB fetch request

### ISSUE THREAD

**Issue by beckpull** [beckpull/break-the-scroll#3]

**Comment by jheersink8** [comment]
Format for API URL = https://opentdb.com/api.php?amount={response#}&category={category(9-32)}&difficulty={easy/medium/hard}&token{GeneratedToken}

Found a limitation where the API only allows requests every 5 seconds, but we are going to retry the request continually until the 5 seconds is up. With that in mind, we're ready with both APIs.
