### ISSUE TITLE
Add/format Bored API fetch request

### ISSUE THREAD

**Issue by beckpull** [beckpull/break-the-scroll#4]

**Comment by beckpull** [comment]
Added and formatted this request 👍

**Comment by jheersink8** [comment]
Looks like this one needs a little work. The first fetch sets the parameters for the fetch URL, but then it doesn't work for any requests after the first.

**Comment by jheersink8** [comment]
Looks like this one needs a little work. The first fetch sets the parameters for the fetch URL, but then it doesn't work for any requests after the first.

**Comment by jheersink8** [comment]
Worked as a team to crush this! Good job everyone!
