### ISSUE TITLE
Structure quiz in script.js

### ISSUE THREAD

**Issue by beckpull** [beckpull/break-the-scroll#7]
using Open Trivia DB API as quiz materials

**Comment by beckpull** [comment]
using Open Trivia DB API as quiz materials

**Comment by beckpull** [comment]
randomized question order,  verify correct answers, keep score

**Comment by beckpull** [comment]
bored api functionality at the end of each round - play again or ${data.activity}

**Comment by jheersink8** [comment]
Randomize done. Need to verify correct answers and track them while the timer runs next.

**Comment by jheersink8** [comment]
Just need to add timer and score so they're visible as you play.
